services:
  web:
    build: .
    container_name: myflask-compose
    network_mode: host
    environment:
      - WELCOME_MSG=Привет из Compose
      - REDIS_HOST=localhost
      - REDIS_PORT=6380
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
  redis:
    image: redis:alpine
    network_mode: host
    command: redis-server --port 6380
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]   # или 6379, если порт не менялся
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'

